name: Weekly Stock Report Sender

on:
  schedule:
    # 매주 월요일 아침 8시(한국시간)에 실행 (UTC 기준 23:00)
    - cron: '0 23 * * 0' 
  workflow_dispatch: # 언제든 수동으로도 실행 가능하게 설정

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install finance-datareader pandas

      - name: Run email script
        env:
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }} # 보안 설정
        run: python email_test.py
